# Generated by Django 5.0 on 2023-12-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='things',
            name='slug',
        ),
    ]
