# Generated by Django 5.0 on 2023-12-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaz', '0002_remove_things_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Things',
            new_name='Thing',
        ),
    ]
