# Generated by Django 5.0 on 2023-12-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaz', '0003_rename_things_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
